import { authTables } from "@convex-dev/auth/server";
import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

const workspaceRole = v.union(
  v.literal("owner"),
  v.literal("admin"),
  v.literal("analyst"),
  v.literal("viewer"),
);
const sourceStatus = v.union(
  v.literal("healthy"),
  v.literal("degraded"),
  v.literal("stale"),
  v.literal("blocked"),
  v.literal("not_connected"),
  v.literal("planned"),
);
const scoreStage = v.union(
  v.literal("insufficient_history"),
  v.literal("emerging"),
  v.literal("rising"),
  v.literal("peaking"),
  v.literal("declining"),
  v.literal("discount_led"),
  v.literal("stable"),
);
const raw = v.any();

export default defineSchema({
  ...authTables,
  workspaces: defineTable({
    name: v.string(),
    slug: v.string(),
    country: v.string(),
    currency: v.string(),
    locale: v.string(),
    timezone: v.string(),
    demo: v.boolean(),
    createdAt: v.number(),
  }).index("by_slug", ["slug"]),
  workspaceMembers: defineTable({
    workspaceId: v.id("workspaces"),
    userId: v.id("users"),
    role: workspaceRole,
    joinedAt: v.number(),
  })
    .index("by_workspace", ["workspaceId"])
    .index("by_user", ["userId"])
    .index("by_user_and_workspace", ["userId", "workspaceId"]),
  businessProfiles: defineTable({
    workspaceId: v.id("workspaces"),
    businessType: v.string(),
    targetCustomer: v.string(),
    audiences: v.array(v.string()),
    categories: v.array(v.string()),
    priceBands: v.array(
      v.object({
        name: v.string(),
        min: v.number(),
        max: v.optional(v.number()),
      }),
    ),
    markets: v.array(v.string()),
    competitors: v.array(v.string()),
    desiredGrossMargin: v.number(),
    normalMoq: v.number(),
    leadTimeDays: v.number(),
    riskTolerance: v.string(),
    onboardingComplete: v.boolean(),
    updatedAt: v.number(),
  }).index("by_workspace", ["workspaceId"]),
  sources: defineTable({
    key: v.string(),
    name: v.string(),
    accessMethod: v.string(),
    credentialsRequired: v.array(v.string()),
    publicAccess: v.boolean(),
    status: sourceStatus,
    complianceStatus: v.string(),
    reliabilityWeight: v.number(),
    latestError: v.optional(v.string()),
    lastSuccessfulRunAt: v.optional(v.number()),
    configuredIntervalHours: v.number(),
    demo: v.boolean(),
  })
    .index("by_key", ["key"])
    .index("by_status", ["status"]),
  sourceMarkets: defineTable({
    sourceId: v.id("sources"),
    country: v.string(),
    currency: v.string(),
    locale: v.string(),
    geoContext: v.optional(v.string()),
  })
    .index("by_source", ["sourceId"])
    .index("by_country", ["country"]),
  sourceSurfaces: defineTable({
    sourceId: v.id("sources"),
    marketId: v.id("sourceMarkets"),
    name: v.string(),
    url: v.string(),
    listSize: v.optional(v.number()),
    rankMeaning: v.string(),
    active: v.boolean(),
  }).index("by_source", ["sourceId"]),
  sourceCategories: defineTable({
    sourceId: v.id("sources"),
    surfaceId: v.optional(v.id("sourceSurfaces")),
    externalId: v.string(),
    name: v.string(),
    url: v.string(),
    active: v.boolean(),
  }).index("by_source", ["sourceId"]),
  crawlRuns: defineTable({
    sourceId: v.id("sources"),
    startedAt: v.number(),
    finishedAt: v.optional(v.number()),
    status: v.string(),
    fetched: v.number(),
    extracted: v.number(),
    inserted: v.number(),
    duplicates: v.number(),
    metrics: raw,
    parserVersion: v.string(),
    error: v.optional(v.string()),
  }).index("by_source_and_started_at", ["sourceId", "startedAt"]),
  sourceHealthEvents: defineTable({
    sourceId: v.id("sources"),
    occurredAt: v.number(),
    severity: v.string(),
    kind: v.string(),
    message: v.string(),
    metrics: raw,
    resolvedAt: v.optional(v.number()),
  }).index("by_source_and_occurred_at", ["sourceId", "occurredAt"]),
  canonicalProducts: defineTable({
    workspaceId: v.id("workspaces"),
    canonicalKey: v.string(),
    title: v.string(),
    brand: v.string(),
    model: v.optional(v.string()),
    gtin: v.optional(v.string()),
    brandSku: v.optional(v.string()),
    country: v.string(),
    demo: v.boolean(),
    firstSeenAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_workspace", ["workspaceId"])
    .index("by_workspace_and_key", ["workspaceId", "canonicalKey"]),
  productListings: defineTable({
    workspaceId: v.id("workspaces"),
    canonicalProductId: v.id("canonicalProducts"),
    sourceId: v.id("sources"),
    sourceProductId: v.string(),
    url: v.string(),
    title: v.string(),
    brand: v.string(),
    category: v.string(),
    country: v.string(),
    currency: v.string(),
    locale: v.string(),
    geoContext: v.optional(v.string()),
    imageUrl: v.optional(v.string()),
    active: v.boolean(),
    rawLatest: raw,
    firstSeenAt: v.number(),
    lastObservedAt: v.number(),
  })
    .index("by_workspace", ["workspaceId"])
    .index("by_workspace_and_source_product", [
      "workspaceId",
      "sourceId",
      "sourceProductId",
    ])
    .index("by_canonical_product", ["canonicalProductId"])
    .index("by_source", ["sourceId"]),
  productVariants: defineTable({
    workspaceId: v.id("workspaces"),
    listingId: v.id("productListings"),
    externalId: v.optional(v.string()),
    colourway: v.optional(v.string()),
    size: v.optional(v.string()),
    gtin: v.optional(v.string()),
    sku: v.optional(v.string()),
  }).index("by_listing", ["listingId"]),
  productImages: defineTable({
    workspaceId: v.id("workspaces"),
    canonicalProductId: v.id("canonicalProducts"),
    listingId: v.optional(v.id("productListings")),
    url: v.string(),
    perceptualHash: v.optional(v.string()),
    isPrimary: v.boolean(),
  }).index("by_product", ["canonicalProductId"]),
  listingSnapshots: defineTable({
    workspaceId: v.id("workspaces"),
    listingId: v.id("productListings"),
    sourceId: v.id("sources"),
    idempotencyKey: v.string(),
    observedAt: v.number(),
    ingestedAt: v.number(),
    price: v.number(),
    originalPrice: v.optional(v.number()),
    currency: v.string(),
    rating: v.optional(v.number()),
    reviewCount: v.optional(v.number()),
    rank: v.optional(v.number()),
    rankPercentile: v.optional(v.number()),
    surfaceSize: v.optional(v.number()),
    availability: v.string(),
    sizesAvailable: v.array(v.string()),
    raw,
    demo: v.boolean(),
  })
    .index("by_idempotency_key", ["idempotencyKey"])
    .index("by_listing_and_observed_at", ["listingId", "observedAt"])
    .index("by_workspace_and_observed_at", ["workspaceId", "observedAt"]),
  sizeAvailabilitySnapshots: defineTable({
    workspaceId: v.id("workspaces"),
    listingSnapshotId: v.id("listingSnapshots"),
    listingId: v.id("productListings"),
    observedAt: v.number(),
    size: v.string(),
    available: v.boolean(),
  }).index("by_listing_and_observed_at", ["listingId", "observedAt"]),
  productAttributes: defineTable({
    workspaceId: v.id("workspaces"),
    canonicalProductId: v.id("canonicalProducts"),
    attributes: raw,
    extractionMethod: v.string(),
    modelVersion: v.optional(v.string()),
    promptVersion: v.optional(v.string()),
    confidence: v.number(),
    materialHash: v.string(),
    humanCorrected: v.boolean(),
    extractedAt: v.number(),
  }).index("by_product", ["canonicalProductId"]),
  attributeCorrections: defineTable({
    workspaceId: v.id("workspaces"),
    productAttributeId: v.id("productAttributes"),
    field: v.string(),
    previousValue: raw,
    correctedValue: raw,
    correctedBy: v.id("users"),
    correctedAt: v.number(),
  }).index("by_attribute", ["productAttributeId"]),
  exactProductMatches: defineTable({
    workspaceId: v.id("workspaces"),
    leftProductId: v.id("canonicalProducts"),
    rightProductId: v.id("canonicalProducts"),
    method: v.string(),
    score: v.number(),
    evidence: v.array(v.string()),
    reviewedStatus: v.string(),
    reviewedBy: v.optional(v.id("users")),
  })
    .index("by_left_product", ["leftProductId"])
    .index("by_right_product", ["rightProductId"]),
  styleClusters: defineTable({
    workspaceId: v.id("workspaces"),
    name: v.string(),
    slug: v.string(),
    primaryCategory: v.string(),
    productType: v.string(),
    keyAttributes: v.array(v.string()),
    priceMin: v.number(),
    priceMax: v.number(),
    imageUrls: v.array(v.string()),
    demo: v.boolean(),
    createdAt: v.number(),
  })
    .index("by_workspace", ["workspaceId"])
    .index("by_workspace_and_slug", ["workspaceId", "slug"]),
  styleClusterMembers: defineTable({
    workspaceId: v.id("workspaces"),
    clusterId: v.id("styleClusters"),
    canonicalProductId: v.id("canonicalProducts"),
    score: v.number(),
    method: v.string(),
  })
    .index("by_cluster", ["clusterId"])
    .index("by_product", ["canonicalProductId"]),
  trendScoresDaily: defineTable({
    workspaceId: v.id("workspaces"),
    clusterId: v.id("styleClusters"),
    date: v.string(),
    score: v.optional(v.number()),
    stage: scoreStage,
    confidence: v.number(),
    version: v.string(),
    components: raw,
    evidenceSnapshotIds: v.array(v.id("listingSnapshots")),
    explanation: v.string(),
  })
    .index("by_cluster_and_date", ["clusterId", "date"])
    .index("by_workspace_and_date", ["workspaceId", "date"]),
  opportunityScoresDaily: defineTable({
    workspaceId: v.id("workspaces"),
    clusterId: v.id("styleClusters"),
    date: v.string(),
    score: v.optional(v.number()),
    saturation: v.number(),
    version: v.string(),
    components: raw,
  })
    .index("by_cluster_and_date", ["clusterId", "date"])
    .index("by_workspace_and_date", ["workspaceId", "date"]),
  trendEvidence: defineTable({
    workspaceId: v.id("workspaces"),
    clusterId: v.id("styleClusters"),
    trendScoreId: v.id("trendScoresDaily"),
    sourceId: v.id("sources"),
    listingId: v.id("productListings"),
    snapshotId: v.id("listingSnapshots"),
    observedAt: v.number(),
    kind: v.string(),
    summary: v.string(),
    sourceUrl: v.string(),
  })
    .index("by_cluster", ["clusterId"])
    .index("by_trend_score", ["trendScoreId"]),
  recommendations: defineTable({
    workspaceId: v.id("workspaces"),
    clusterId: v.optional(v.id("styleClusters")),
    action: v.string(),
    title: v.string(),
    rationale: v.string(),
    confidence: v.number(),
    evidenceIds: v.array(v.id("trendEvidence")),
    assumptions: v.array(v.string()),
    createdAt: v.number(),
    status: v.string(),
  }).index("by_workspace_and_created_at", ["workspaceId", "createdAt"]),
  recommendationOutcomes: defineTable({
    workspaceId: v.id("workspaces"),
    recommendationId: v.id("recommendations"),
    outcome: v.string(),
    metric: v.optional(v.number()),
    notes: v.optional(v.string()),
    recordedAt: v.number(),
  }).index("by_recommendation", ["recommendationId"]),
  ownCatalogProducts: defineTable({
    workspaceId: v.id("workspaces"),
    externalId: v.string(),
    title: v.string(),
    category: v.string(),
    price: v.number(),
    cost: v.optional(v.number()),
    attributes: raw,
  })
    .index("by_workspace", ["workspaceId"])
    .index("by_workspace_and_external_id", ["workspaceId", "externalId"]),
  ownInventorySnapshots: defineTable({
    workspaceId: v.id("workspaces"),
    catalogProductId: v.id("ownCatalogProducts"),
    observedAt: v.number(),
    units: v.number(),
    raw,
  }).index("by_product_and_observed_at", ["catalogProductId", "observedAt"]),
  ownSalesDaily: defineTable({
    workspaceId: v.id("workspaces"),
    catalogProductId: v.id("ownCatalogProducts"),
    date: v.string(),
    units: v.number(),
    revenue: v.number(),
    returns: v.optional(v.number()),
  }).index("by_product_and_date", ["catalogProductId", "date"]),
  supplierConstraints: defineTable({
    workspaceId: v.id("workspaces"),
    category: v.string(),
    minOrderQuantity: v.number(),
    leadTimeDays: v.number(),
    unitCost: v.optional(v.number()),
    notes: v.optional(v.string()),
  }).index("by_workspace", ["workspaceId"]),
  savedViews: defineTable({
    workspaceId: v.id("workspaces"),
    userId: v.id("users"),
    name: v.string(),
    route: v.string(),
    filters: raw,
    createdAt: v.number(),
  }).index("by_workspace_and_user", ["workspaceId", "userId"]),
  alertRules: defineTable({
    workspaceId: v.id("workspaces"),
    userId: v.id("users"),
    name: v.string(),
    kind: v.string(),
    threshold: v.number(),
    filters: raw,
    active: v.boolean(),
    channels: v.array(v.string()),
    createdAt: v.number(),
  }).index("by_workspace", ["workspaceId"]),
  alertEvents: defineTable({
    workspaceId: v.id("workspaces"),
    ruleId: v.id("alertRules"),
    occurredAt: v.number(),
    title: v.string(),
    message: v.string(),
    evidenceIds: v.array(v.id("trendEvidence")),
    readAt: v.optional(v.number()),
  }).index("by_workspace_and_occurred_at", ["workspaceId", "occurredAt"]),
  researchQueries: defineTable({
    workspaceId: v.id("workspaces"),
    userId: v.id("users"),
    question: v.string(),
    filters: raw,
    createdAt: v.number(),
  }).index("by_workspace_and_created_at", ["workspaceId", "createdAt"]),
  researchAnswers: defineTable({
    workspaceId: v.id("workspaces"),
    queryId: v.id("researchQueries"),
    answer: v.string(),
    confidence: v.number(),
    assumptions: v.array(v.string()),
    evidenceIds: v.array(v.id("trendEvidence")),
    toolCalls: v.array(v.string()),
    createdAt: v.number(),
  }).index("by_query", ["queryId"]),
  scoringConfigs: defineTable({
    workspaceId: v.id("workspaces"),
    category: v.optional(v.string()),
    trendWeights: raw,
    saturationWeights: raw,
    opportunityWeights: raw,
    minObservationCount: v.number(),
    minHistoryDays: v.number(),
    version: v.string(),
    updatedAt: v.number(),
  }).index("by_workspace", ["workspaceId"]),
  importRuns: defineTable({
    workspaceId: v.id("workspaces"),
    userId: v.optional(v.id("users")),
    fileName: v.string(),
    startedAt: v.number(),
    finishedAt: v.optional(v.number()),
    totalRows: v.number(),
    insertedRows: v.number(),
    duplicateRows: v.number(),
    invalidRows: v.number(),
    errors: v.array(raw),
    status: v.string(),
  }).index("by_workspace_and_started_at", ["workspaceId", "startedAt"]),
  reports: defineTable({
    workspaceId: v.id("workspaces"),
    periodStart: v.string(),
    periodEnd: v.string(),
    title: v.string(),
    sections: raw,
    createdAt: v.number(),
  }).index("by_workspace_and_period_end", ["workspaceId", "periodEnd"]),
});
